esphome:
  name: esphome-web-745c70
  friendly_name: LILYGO RS485
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configure uart that will be used
uart:
  - id: mod_bus
    rx_pin: GPIO21
    tx_pin: GPIO22
    baud_rate: 115200
    data_bits: 8
    stop_bits: 1
    parity: NONE

modbus:
  - uart_id: mod_bus
    id: modbus1
    send_wait_time: 200ms

modbus_controller:
  - id: marstek_venus
    address: 0x1
    modbus_id: modbus1
    command_throttle: 200ms
    update_interval: 1s

#modbus registers
# range 31000-
text_sensor:
   - name: "Marstek device name"
     icon: "mdi:information"
     platform: modbus_controller
     modbus_controller_id: marstek_venus
     register_type: holding
     address: 31000
     register_count: 1
     response_size: 20
     skip_updates: 30

#binary_sensor:
  #huawei example , kan gebruikt worden  voor alarm codes, fault word en grid standards 
  # Range 32000 - 32019 (1/2)
  # Register 32000
  # - name: "Huawei inverter state standby"
  #   icon: "mdi:information"
  #   platform: modbus_controller
  #   modbus_controller_id: marstek_venus
  #   register_type: holding
  #   address: 32000
  #   bitmask: 0x001
  # - name: "Huawei inverter state grid-connected"
  #   icon: "mdi:information"
  #   platform: modbus_controller
  #   modbus_controller_id: marstek_venus
  #   register_type: holding
  #   address: 32000
  #   bitmask: 0x002
  # - name: "Huawei inverter state grid-connected normally"
  #   icon: "mdi:information"
  #   platform: modbus_controller
  #   modbus_controller_id: marstek_venus
  #   register_type: holding
  #   address: 32000
  #   bitmask: 0x004
  # - name: "Huawei inverter state grid connection with derating due to power rationing"
  #   icon: "mdi:information"
  #   platform: modbus_controller
  #   modbus_controller_id: marstek_venus
  #   register_type: holding
  #   address: 32000
  #   bitmask: 0x008

sensor:
  - name: "Battery State of Charge"
    platform: modbus_controller
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 32104  # Register address for Battery SOC
    value_type: U_WORD  # Unsigned 16-bit value
    unit_of_measurement: "%"
    accuracy_decimals: 1
    skip_updates: 30

  - name: "Marstek total charging energy"
    platform: modbus_controller
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 33000
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    skip_updates: 30
    filters:
      - multiply: 0.01
  - name: "Marstek total discharging energy"
    platform: modbus_controller
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 33002
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    skip_updates: 30
    filters:
      - multiply: 0.01

select:
  - platform: modbus_controller
    name: "Marstek forcible charge/discharge"
    modbus_controller_id: marstek_venus
    address: 42010
    value_type: U_WORD
    optionsmap:
      "Stop": 0
      "Charge": 1
      "Discharge": 2
    skip_updates: 10
