esphome:
  name: esphome-web-745c70
  friendly_name: LILYGO RS485
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configure uart that will be used
uart:
  - id: mod_bus
    rx_pin: GPIO21
    tx_pin: GPIO22
    baud_rate: 115200
    data_bits: 8
    stop_bits: 1
    parity: NONE

modbus:
  - uart_id: mod_bus
    id: modbus1
    send_wait_time: 200ms

modbus_controller:
  - id: marstek_venus
    address: 0x1
    modbus_id: modbus1
    command_throttle: 200ms
    update_interval: 1s

text_sensor:
   - name: "Marstek device name"
     icon: "mdi:information"
     platform: modbus_controller
     modbus_controller_id: marstek_venus
     register_type: holding
     address: 31000
     register_count: 1
     response_size: 20
     skip_updates: 30

binary_sensor:
  - platform: modbus_controller
    name: "Marstek Battery Protection Active"
    icon: "mdi:information"
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 44001
    bitmask: 0x01
    skip_updates: 30
  - platform: modbus_controller
    name: "Marstek Battery Overvoltage Warning"
    icon: "mdi:information"
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 44002
    bitmask: 0x02
    skip_updates: 30
  - platform: modbus_controller
    name: "Battery Undervoltage Warning"
    icon: "mdi:information"
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 44003
    bitmask: 0x04
    skip_updates: 30


sensor:
  - name: "Marstek Battery State of Charge"
    icon: mdi:battery-70
    platform: modbus_controller
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 32104  # Register address for Battery SOC
    value_type: U_WORD  # Unsigned 16-bit value
    unit_of_measurement: "%"
    accuracy_decimals: 1
    skip_updates: 30
  - name: "Marstek total charging energy"
    platform: modbus_controller
    icon: mdi:battery-arrow-up
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 33000
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    skip_updates: 30
    filters:
      - multiply: 0.01
  - name: "Marstek total discharging energy"
    platform: modbus_controller
    icon: mdi:battery-arrow-down
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 33002
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    skip_updates: 30
    filters:
      - multiply: 0.01

select:
  - platform: modbus_controller
    name: "Marstek forcible charge/discharge"
    icon: mdi:swap-horizontal
    modbus_controller_id: marstek_venus
    address: 42010
    value_type: U_WORD
    optionsmap:
      "Stop": 0
      "Charge": 1
      "Discharge": 2
    skip_updates: 10

# number:
#   - platform: modbus_controller
#     name: "Marstek forcible charge power"
#     icon: mdi:tune-variant
#     modbus_controller_id: marstek_venus
#     register_type: holding
#     address: 42011
#     value_type: U_WORD
#     unit_of_measurement: "W"
#     min_value: 0
#     max_value: 2500
#     step: 50
#     write_lambda: |-
#       // Convert the value to an integer explicitly
#       return uint16_t(x);
#   - platform: modbus_controller
#     name: "Marstek forcible discharge power"
#     icon: mdi:tune-variant
#     modbus_controller_id: marstek_venus
#     register_type: holding
#     address: 42020
#     value_type: U_WORD
#     unit_of_measurement: "W"
#     min_value: 0
#     max_value: 2500
#     step: 50
#     write_lambda: |-
#       // Convert the value to an integer explicitly
#       return uint16_t(x);

switch:
  - platform: modbus_controller
    name: "Marstek RS485 Control Mode"
    icon: mdi:transfer
    modbus_controller_id: marstek_venus
    register_type: holding
    address: 42000
    write_lambda: |-
      if (x) {
        // Enable RS485 control mode
        return 0x55AA;
      } else {
        // Disable RS485 control mode
        return 0x55BB;
      }